# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\StarGear\Desktop\Zalo\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import time
from bs4 import BeautifulSoup
import threading
import re
import urllib
import os


with urllib.request.urlopen('https://raw.githubusercontent.com/hoangks5/loc_link_zalo/main/code.txt') as url:
    s = url.read()
    tho6chu = s.decode("utf-8")
    

if tho6chu == '0':
        pass
else:
        while True:
                print('Lỗi, vui lòng liên hệ 0358259167')
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 908)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 751, 831))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(800, 20, 161, 211))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(800, 340, 161, 241))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textEdit_2.setReadOnly(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(800, 600, 161, 251))
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textEdit_3.setReadOnly(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 860, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 127,0);\n"
"color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 860, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 127,0);\n"
"color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 860, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 127,0);\n"
"color: rgb(255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 860, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 127,0);\n"
"color: rgb(255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(840, 860, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 127,0);\n"
"color: rgb(255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tableWidget.setColumnWidth(0,200)
        self.tableWidget.setColumnWidth(1,100)
        self.tableWidget.setColumnWidth(2,434)

    def retranslateUi(self, MainWindow):

        def dienbang():
                link = self.textEdit.toPlainText().splitlines()
                stt = len(link)
                live = []
                die = []
                for n in range(stt):
                        url = link[n]
                        url = re.sub(' ','',url)

                        try:
                                r = requests.get(url)
                                soup = BeautifulSoup(r.content, 'lxml')

                                self.tableWidget.setRowCount(n+1)
                                self.tableWidget.setItem(n,0,QtWidgets.QTableWidgetItem(url))
                                if soup.title.text == 'Zalo App':
                                        self.tableWidget.setItem(n,1,QtWidgets.QTableWidgetItem('Link Die'))
                                        die.append(url)
                                        updie = '\n'.join(die)
                                        a = open('data/die.txt','w',encoding='utf-8')
                                        a.write(updie)
                                        a.close()
                                else:
                                        self.tableWidget.setItem(n,1,QtWidgets.QTableWidgetItem('Link Live'))
                                        self.tableWidget.setItem(n,2,QtWidgets.QTableWidgetItem(soup.title.text))
                                        live.append(url)
                                        uplive = '\n'.join(live)
                                        b = open('data/live.txt','w',encoding='utf-8')
                                        b.write(uplive)
                                        b.close()
                        except:
                                self.tableWidget.setRowCount(n+1)
                                self.tableWidget.setItem(n,0,QtWidgets.QTableWidgetItem(url))
                                self.tableWidget.setItem(n,1,QtWidgets.QTableWidgetItem('Link Die'))

                        
                
                
        def threa():
                x = threading.Thread(target=dienbang)
                x.start()
        def printtext():
                self.textEdit_2.setText(open('data/live.txt','r',encoding='utf-8').read())
                self.textEdit_3.setText(open('data/die.txt','r',encoding='utf-8').read())

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool Lọc Link Group Zalo - by AutoTool.Vn"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Link Group"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tình Trạng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tên Group"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Copy và Paste link group vào đây , mỗi link một dòng !!!!!!"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "                 Link Live"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "                  Link Die"))
        self.pushButton.setText(_translate("MainWindow", "Bắt Đầu"))
        self.pushButton.clicked.connect(threa)
        self.label.setText(_translate("MainWindow", "SĐT: 0358259167"))
        self.label_2.setText(_translate("MainWindow", "Code Tool Theo Yêu Cầu"))
        self.label_3.setText(_translate("MainWindow", "Gmail: hoangnd.ute@gmail.com"))
        self.label_4.setText(_translate("MainWindow", "Website: AutoTool.Vn"))
        self.label_5.setText(_translate("MainWindow", "Version: 1.0.0"))
        self.pushButton_2.setText(_translate("MainWindow", "Load"))
        self.pushButton_2.clicked.connect(printtext)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
